### ISSUE TITLE
Build fails on Ubuntu 23.04 because pcap_compile_nopcap is deprecated

### ISSUE THREAD

**Issue by Stealthmate** [f18m/large-pcap-analyzer#15]
```Dockerfile
FROM docker-hub-mirror.linecorp.com/ubuntu:23.04

RUN wget https://github.com/f18m/large-pcap-analyzer/archive/3.7.1.tar.gz \
  && tar xvzf 3.7.1.tar.gz \
  && cd large-pcap-analyzer-3.7.1/ \
  && ./configure && make
```

Apparently `pcap_compile_nopcap` got deprecated six months ago in `libpcap` v1.11.0: https://github.com/the-tcpdump-group/libpcap/blob/753dc6beddea935c4f0365c3e8634b44db527a82/CHANGES#L19

I don't know what version Ubuntu 23.04 is using but I got a deprecation error when I tried to build. Building with 22.10 works fine.

**Comment by f18m** [comment]
hi @Stealthmate ,
sorry for the delay. I think I fixed the build issue... can you try to build on your Ubuntu 23.04 the branch "bugfix/15" of this repository?
I think it should work just fine. Here's the PR: https://github.com/f18m/large-pcap-analyzer/pull/17

Thanks

**Comment by f18m** [comment]
Assuming it works fine, I'm merging #17
