### ISSUE TITLE
build requires automake 1.15, which is not easily available on CentOS 7

### ISSUE THREAD

**Issue by ezonakiusagi** [f18m/large-pcap-analyzer#3]
trying to build this on CentOS 7, i get:

$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /large-pcap-analyzer/missing aclocal-1.15 -I m4
/large-pcap-analyzer/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [aclocal.m4] Error 127

the packaged version available is:

$ aclocal --version
aclocal (GNU automake) 1.13.4
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

system is:

$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 

Is it possible to allow this to build on CentOS 7 without having to upgrade automake/autoconf on CentOS 7?

**Comment by f18m** [comment]
Should be fixed in latest master branch... can you verify?

Thanks

**Comment by ezonakiusagi** [comment]
Yes! builds on CentOS7 now. Thank you for quick response!

**Comment by ezonakiusagi** [comment]
i know you made changes to use automake 1.13 so this would build on centos 7, however, now it has problems with Fedora 26 that only has automake 1.15. i don't know if there any reason to make this so version specific, perhaps a more version neutral requirement for automake would help?
