### ISSUE TITLE
Is there a way to get  a list of the installed programs by analyzing the pcap file ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [f18m/large-pcap-analyzer#8]

**Comment by f18m** [comment]
Sorry what does this mean? installed programs inside a PCAP file?

**Comment by minanagehsalalma** [comment]
> Sorry what does this mean? installed programs inside a PCAP file?

It contains network traffic of monitoring a windows device.

**Comment by f18m** [comment]
Hi @minanagehsalalma you will need to use Wireshark for that!

**Comment by minanagehsalalma** [comment]
> you will need to use Wireshark for that!

@f18m  Which with filters ?

And what urls list to connect the programs to ? 

Also i need it to be somewhat more friendly which isn't available with Wireshark.
